name: "Main Terraform"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "terraform-692614315984-statefile"
      aws-statefile-key: "env:/dev/rds/terraform.tfstate"
      aws-lock-dynamodb-table: "692614315984-terraform-lock"
      destroy: "false"
      aws-assume-role-arn: "arn:aws:iam::692614315984:role/TechChallenge-Fase4-Role"